# Generated by Django 5.2 on 2025-04-19 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='posts_images')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instra.userregister')),
            ],
        ),
    ]
