# Generated by Django 5.2 on 2025-04-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instra', '0002_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosttModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='media/posts_images')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instra.userregister')),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
