# Generated by Django 5.2 on 2025-04-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instra', '0003_posttmodel_delete_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttmodel',
            old_name='name',
            new_name='nameuser',
        ),
    ]
