# Generated by Django 5.2 on 2025-04-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instra', '0004_rename_name_posttmodel_nameuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posttmodel',
            name='description',
            field=models.TextField(default='Instgram_Post', max_length=150),
        ),
    ]
